---
- name: install packages
  apt:
    name: "{{ apt_packages }}"
    update_cache: true

- name: put requirements file for pip
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: install pip packages
  pip:
    requirements: /tmp/requirements.txt

- name: extract terraform
  unarchive:
    remote_src: true
    src: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    owner: vagrant
    group: vagrant

- name: create aws directory
  file:
    dest: "{{ install_dir }}"
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant
